/*  A triangular number can also be generated by the formula
    
        triangularNumber = n * (n - 1) / 2;
    
    for any integer value of n. For example the 10th triangular number, 55, can
    be generated by substituting 10 as the value for n in the prceding formula.
    
    Write a program that generates a table fo triangular numbers using the
    preceding formula. Have the program generate every fifth triangular number
    between 5 and 50 (that is 5, 10, 15, ..., 50).                           */
    
# include <stdio.h>

int main(void)
{
    int n, number;
    
    printf ("TABLE OF TRIANGULAR NUMBERS\n\n");
    printf (" n     Triangular number\n");
    printf ("---    -----------------\n");
    
    for (n = 5; n <= 50; n += 5)
        printf ("%3i       %9i\n", n, n * (n + 1) / 2);
        
    return 0;
}
